name: hdulib

on:
  schedule:
    - cron: "03 01 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify main.py exists
        run: |
          if [ ! -f main.py ]; then echo "main.py not found"; exit 1; fi

      - name: Run script
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: python main.py
